/*
 * Trivální build bez závislostí: spojí vendor/chess.js + vendor/pieces.js
 * + src/plugin.js do kořenového main.js, který načítá Obsidian.
 *
 * Spuštění:
 *   node build.mjs             – jen sestaví main.js
 *   node build.mjs --deploy    – navíc nakopíruje main.js/manifest.json/styles.css
 *                                do vaultu (cesta z deploy.local.json nebo
 *                                z env LBT_DEPLOY_DIR)
 *
 * deploy.local.json (gitignored):  { "dir": "C:/…/.obsidian/plugins/lichess-blunder-trainer" }
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync, copyFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const read = (p) => readFileSync(join(here, p), "utf8");

// chess.js (CJS) – zabalíme do IIFE s vlastním module/exports
const chessSrc = read("vendor/chess.js");
const piecesSrc = read("vendor/pieces.js");
const pluginSrc = read("src/plugin.js");

const chessWrapped = `
const CHESS = (function () {
	const module = { exports: {} };
	let exports = module.exports;
${chessSrc}
	return module.exports.Chess;
})();
`;

const piecesWrapped = `
const PIECES = (function () {
	const module = { exports: {} };
	let exports = module.exports;
${piecesSrc}
	return module.exports;
})();
`;

const out = `/* Lichess Blunder Trainer — generated by build.mjs. Neupravuj ručně, edituj src/plugin.js. */
"use strict";
${chessWrapped}
${piecesWrapped}
${pluginSrc}
`;

writeFileSync(join(here, "main.js"), out);
console.log("main.js zapsán (" + out.length + " B)");

// --- volitelné nasazení do vaultu ---
const wantDeploy = process.argv.includes("--deploy") || process.argv.includes("-d");
if (wantDeploy) {
	let target = process.env.LBT_DEPLOY_DIR || "";
	if (!target && existsSync(join(here, "deploy.local.json"))) {
		try {
			target = JSON.parse(read("deploy.local.json")).dir || "";
		} catch (e) {
			console.error("deploy.local.json nejde přečíst:", e.message);
		}
	}
	if (!target) {
		console.error(
			"--deploy: chybí cíl. Vytvoř deploy.local.json  { \"dir\": \"<vault>/.obsidian/plugins/lichess-blunder-trainer\" }  nebo nastav LBT_DEPLOY_DIR."
		);
		process.exit(1);
	}
	if (!existsSync(target)) mkdirSync(target, { recursive: true });
	for (const f of ["main.js", "manifest.json", "styles.css"]) {
		copyFileSync(join(here, f), join(target, f));
	}
	// prázdný .hotreload => plugin Hot Reload (pjeby/hot-reload) plugin sám
	// překlopí po každém buildu; bez toho pluginu je soubor neškodný
	if (!existsSync(join(target, ".hotreload"))) writeFileSync(join(target, ".hotreload"), "");
	console.log("nasazeno do: " + target);

	// volitelně: doprovodný Templater user script do vaultu
	let tdir = process.env.LBT_TEMPLATER_DIR || "";
	if (!tdir && existsSync(join(here, "deploy.local.json"))) {
		try {
			tdir = JSON.parse(read("deploy.local.json")).templaterDir || "";
		} catch (e) {
			/* už zalogováno výše */
		}
	}
	if (tdir) {
		if (!existsSync(tdir)) mkdirSync(tdir, { recursive: true });
		for (const f of ["lichessBlunderCallout.js", "lichess-config.example.json"]) {
			copyFileSync(join(here, "extras", "templater", f), join(tdir, f));
		}
		console.log("templater script nasazen do: " + tdir);
	}
}
