/*
 * Trivální build bez závislostí: spojí vendor/chess.js + vendor/pieces.js
 * + src/plugin.js do kořenového main.js, který načítá Obsidian.
 *
 * Spuštění:  node build.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const read = (p) => readFileSync(join(here, p), "utf8");

// chess.js (CJS) – zabalíme do IIFE s vlastním module/exports
const chessSrc = read("vendor/chess.js");
const piecesSrc = read("vendor/pieces.js");
const pluginSrc = read("src/plugin.js");

const chessWrapped = `
const CHESS = (function () {
	const module = { exports: {} };
	let exports = module.exports;
${chessSrc}
	return module.exports.Chess;
})();
`;

const piecesWrapped = `
const PIECES = (function () {
	const module = { exports: {} };
	let exports = module.exports;
${piecesSrc}
	return module.exports;
})();
`;

// z pluginu odstraníme jen úvodní blokový komentář kvůli přehlednosti (nepovinné)
const out = `/* Lichess Blunder Trainer — generated by build.mjs. Neupravuj ručně, edituj src/plugin.js. */
"use strict";
${chessWrapped}
${piecesWrapped}
${pluginSrc}
`;

writeFileSync(join(here, "main.js"), out);
console.log("main.js zapsán (" + out.length + " B)");
